### PR TITLE
OpenAPI spec

### PR DESCRIPTION
**Pull request by Superpat**
## Purpose

Add draft Open API spec for #3 . Does not include the azure specific bits though.

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by Superpat** [comment]
@microsoft-github-policy-service agree

**Comment by pamelafox** [comment]
Thanks @Superpat ! Can I ask how you generated the spec? I did actually generate some in another repo, based on some Pydantic models, but then I realized it's not possible to correctly document the streaming response. Did you figure it out, or is this just the non-streamed response?

**Comment by Superpat** [comment]
I wrote it by hand as I was reading the readme. I put the streaming response on a different route called /streaming as I did not know how to allow two different response types. I'm not a 100% my implementation of streaming is okay though. A good test would be to try to use openAPI testing tools to see if this spec can test one of the demos.

**Comment by pamelafox** [comment]
Thanks for the additional details, @superpat. This project has now been superceded by https://github.com/microsoft/ai-chat-protocol which has both a JavaScript SDK and the specification README. It also has a TypeSpec file to document the API formally, which I believe can be used to generate documentation:
https://github.com/microsoft/ai-chat-protocol/blob/main/spec/models.tsp

I've been keeping tabs on the OpenAPI effort to support streaming, and it looks like there is progress on that front, but I don't think the PRs have been merged yet to fully support it. We need support for it in OpenAPI before we can have a fully correct OpenAPI.json. We did try to make it more OpenAPI-compatible by changing the protocol to have two different endpoints for streaming vs non-streaming responses, however. The non-streamed response should be fully OpenAPI-documentable.

I'm closing this PR since I'm about to archive this repository. Thanks for your contribution, and please star the new project if you're still interested in this space.

**Pull request closed without merging**
